### ISSUE TITLE
Functions like toString return a collection

### ISSUE THREAD

**Issue by nwhatt** [HL7/fhirpath.js#101]
Based on my understanding of FHIRPath - functions like toString() should not return a collection, they should return a string, toDecimal a decimal, etc. 
http://hl7.org/fhirpath/N1/#tostring-string

In playing with demo and looking at the code - it looks like all functions are forced to return a collection by calling `util.arraify` on them. 

```
      if(!rawParams){
        res = invoc.fn.call(ctx, util.arraify(data));
        return util.arraify(res);
      } else {
        throw new Error(fnName + " expects no params");
      }
```

Am I reading the specification wrong? Is there any other way to force a collection to return a single string?

**Comment by plynchnlm** [comment]
Everything is a collection in FHIRPath, even though it might contain just be one element.  For instance you can do 3.count() and get back (1), since the "3" is implicitly (3).  If you disagree with this behavior, feel free to post your question on chat.fhir.org (on the "fhirpath" stream.
