### ISSUE TITLE
Implement the FHIR hasValue method

### ISSUE THREAD

**Issue by brianpos** [HL7/fhirpath.js#120]
http://hl7.org/fhir/fhirpath.html#functions

**Comment by bholyshevskyi** [comment]
Will this issue be addressed as it seems crucial since `hasValue()` function is used in the very common constraint `ele-1` https://www.hl7.org/fhir/element.html#definition?

**Comment by plynchnlm** [comment]
Thanks for the reminder.

**Comment by yuriy-sedinkin** [comment]
Implemented in version 3.6.0.
