### ISSUE TITLE
impossible to use attribute name that starts with a capitalized letter

### ISSUE THREAD

**Issue by ruscoder** [HL7/fhirpath.js#136]
Hello! 

I'm using `fhirpath.js` library with a FHIR server that allows using first-class extensions with custom name and there is an issue with accessing attributes that starts with a capitalized letter, e.g.

```
fhirpath.evaluate({"resourceType": "Patient", "CustomField": "value"}, "Patient.CustomField", {})
```
returns []

What is the reason for having this restriction?

Thanks.

**Comment by plynchnlm** [comment]
I think the code is assuming that any identifier starting with a capital letter is a resource type.  It is a simplification, but on other hand, I am not aware of any case in FHIR where a property of a resource also starts with a capital letter.  Why would you not follow that pattern for your custom property names?

Anyway, I agree that identifiers starting with a capital letter should work, and I will add it to our list of things to address.

**Comment by ruscoder** [comment]
> Why would you not follow that pattern for your custom property names?

I'm using Aidbox FHIR server that has own format for union type](https://docs.aidbox.app/storage-1/aidbox-and-fhir-formats#union-choice-types) where `valueQuantity: {...}` becomes `{value: {Quantity: {...}}}` and currently it's impossible to extract value.Quantitiy, so, I'm using workaround `value.children()`.

**Comment by ruscoder** [comment]
Thanks for fixing it! It works well in the latest release
