### ISSUE TITLE
Regression: evaluation fails if context/environment contains nulls

### ISSUE THREAD

**Issue by ruscoder** [HL7/fhirpath.js#138]
Hello! 

This expression worked in 2.14.0, but after 2.14.1 it started to fail:
```TypeError: Cannot convert undefined or null to object```

It fails here:
https://github.com/HL7/fhirpath.js/blob/905f0a577b3a71a2449890a49016abe8171e2b42/src/hash-object.js#L43

I assume it happens, because of the bug in the check "typeof null" that return "object" for null as well.

Expression: `QuestionnaireResponse.repeat(item).where(linkId='test').answer.value`

Context:
```json
{
   "resourceType": "QuestionnaireResponse",
   "item": [
      {
         "linkId": "test",
         "answer": [
            {
               "valueInteger": null
            }
         ]
      }
   ]
}
```

**Comment by ruscoder** [comment]
For this particular data it works without using repeat `QuestionnaireResponse.item.where(linkId='test').answer.value`

**Comment by ruscoder** [comment]
I created a PR that fixes it https://github.com/HL7/fhirpath.js/pull/139

**Comment by plynchnlm** [comment]
I don't think that example is valid in FHIR.  See https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/answer.2Evalue.5Bx.5D.3A.20null.3F/near/352536149.

So, I am not sure we should handle this case.

**Comment by plynchnlm** [comment]
Then again, even if this case is not valid, there is a valid case for having a null, per https://build.fhir.org/json.html#primitive, which I suspect would have the same problem.

**Comment by ruscoder** [comment]
Looks like it's fixed and does not fail anymore, thanks

**Comment by plynchnlm** [comment]
Yes, in 3.9.1.  Sorry we did not report back here.
