### ISSUE TITLE
`ofType(Quantity).system.empty()` with a non-empty system still returns true

### ISSUE THREAD

**Issue by vadi2** [HL7/fhirpath.js#146]
Expression context:
```
value
```

Expression fhirpath:
```
ofType(Quantity).system.empty()
```

Resource:

```
{
  "resourceType": "Observation",
  "id": "example",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2018-12-16T22:17:03.3745128+00:00",
    "security": [
      {
        "system": "http://hl7.org/fhir/v3/ActReason",
        "code": "HTEST",
        "display": "test health data"
      }
    ]
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: example</p><p><b>status</b>: final</p><p><b>category</b>: Vital Signs <span>(Details : {http://terminology.hl7.org/CodeSystem/observation-category code 'vital-signs' = 'Vital Signs', given as 'Vital Signs'})</span></p><p><b>code</b>: Body Weight <span>(Details : {LOINC code '29463-7' = 'Body weight', given as 'Body Weight'}; {LOINC code '3141-9' = 'Body weight Measured', given as 'Body weight Measured'}; {SNOMED CT code '27113001' = 'Body weight', given as 'Body weight'}; {http://acme.org/devices/clinical-codes code 'body-weight' = 'body-weight', given as 'Body Weight'})</span></p><p><b>subject</b>: <a>Patient/example</a></p><p><b>encounter</b>: <a>Encounter/example</a></p><p><b>effective</b>: Mar 28, 2016</p><p><b>value</b>: 185 lbs<span> (Details: UCUM code [lb_av] = 'lb_av')</span></p></div>"
  },
  "status": "final",
  "category": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/observation-category",
          "code": "vital-signs",
          "display": "Vital Signs"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "29463-7",
        "display": "Body Weight"
      },
      {
        "system": "http://loinc.org",
        "code": "3141-9",
        "display": "Body weight Measured"
      },
      {
        "system": "http://snomed.info/sct",
        "code": "27113001",
        "display": "Body weight"
      },
      {
        "system": "http://acme.org/devices/clinical-codes",
        "code": "body-weight",
        "display": "Body Weight"
      }
    ]
  },
  "subject": {
    "reference": "Patient/example"
  },
  "encounter": {
    "reference": "Encounter/example"
  },
  "effectiveDateTime": "2016-03-28",
  "valueQuantity": {
    "value": 185,
    "unit": "lbs",
    "system": "http://unitsofmeasuress.org",
    "code": "[lb_av]"
  }
}
```

:test_tube: [Test with FHIRPath-Lab](https://dev.fhirpath-lab.com/FhirPath?parameters=N4IgpgHgDgTmDO8CWB7AdiAXCFAzAKgJ5RgAUAigK4CGaALknYQJQB08h8dYAtq71CalmIADQgAxum4Q6WEADdqAG0pgx4NAHMkaddlwALJDCjU6h1gCt4G7jB66UylFsIBlMDAVf5hunRQ8JgA9CHwAI4uaEYmALQwACys1ABelHAA7mAARsjc8Kx6dCGxMBpKMEjUOcoIWADaALricPAoGRJgAFLtGNjAADogbR0wXUQkw5jDAPJ5XkoM6MOiw0gAJtPDkNQ8UHWrwzxgdNTTQ4peyOgAkltYwwCMRyDK1FwAqlAb5mAPMxAACYAAxPAAccSeQKhADZ8ECgZgngB2TAggDMrAxKMSAFZoeCANQgkHokGveBgCQZRiEaYNS4cLi8bYgfyBUIhQzKFGsFAwLSlYwwEIKDEhACCEjoACUwB8VmJhlINmA2QAJfAAUXc+FeGyQ8AO1HpjxABToAAJDArlBYrb8zsMAL5NF1rC2QOgXYZccyUeBsrRgPQwP4PT2GhRsgA80atEB4yjQ8AAvINM+yAlAuZl86xMliBUKngBOCshCD+ZOZ4YAPljUEbOXrAHFQ14I1aAHLUGDhhg+K2ZRiGK0AEVO1CQyngsZCrYXzabLfrmwXrcwVt2+zqy8bK9b-rogc39e3uF0KgPq9jrYkfy0AsI5+3ADVGCore4kFpU1asbGrQ9akFOZyzvAVrbsAHK5mE9iOGgziuIQrA8nyJYhAAwigaruJw3A8CEKALN45ioGgcSPtwz4wIQVqqmAVoAOQKF+yhxMg-7wCxVppqxn5nMoP5-qmLGiFaOg+GgVofIJHGiTxLEuswC7AWgjYhCuR71kxb5WgAQnhDEAOpgH+-iARpoHgTOc7QVawAADKzLcPbYYxeHMSxQJloksIYnEKJ8QJLHGRsDHZJZdASVJSAyXJUHhSZVrmTFKkANxOa57meUxrEYk8iRPHEZahaxEVRRZWhWQAsgq8AZP8cXSaGSWVal0W1daDUfM1GxZU57g9rMdXahOVrYfgXlqqxQIok8TwYqSTwVSlkUjjV-itQl7XyRt1UZS62WwTmXLUBIJz8oKIRquxXTwCEEjKLoSCPpxTFQQVLE5CZcTdTt-GsX9kUA9tsWSW1skHVVaUQypanhGYmm3rpTU5FY1J0AZsbUPWAAKFGhiUu4HGAC742ja6hlIlD0F4uP49qaB0wzopk-uIRU9ph407guDY3tBl1f2VpAuCkmgk8sLU-e9ZKKoFOLheVoQniVrKHkQEo-WVpgdOkHbp82GfHVs3MQ0WsAPrUAoTTAyxNt2yxSM2bed0JfWrqeiegZsleaAqK8NFgHRZqYIyKp4boWgMkyhGsuacFcohTguG46G8jdQq4fhifEaRVLkcsVGh+HIfeWy7HCVxYlBsqICGsa7wR8MQnfr+PGuu6LTR2qvqSDH2jx36BdsinYQuLoEg55XA-mn5AVBSiBpGiabcgHD6U9T7CcsjwE-nVPKAz3PjdMWyRUlWVa8t6abJw4DvWNQNe9jwfR+cmE8DIScGysF0LgFA4QZTz3VIvRay1Vp3w3o-LqEN34gGZERL+8FuZXTADnO6YAHoIGeq9NA70VDUW8g3T0l9zSg0IODGKsDW7wM2jvfwPcPR+koJjbGg84CCzgKzCBgIiYMBJiETmEC2GaDZvYbhYBeG0wEcMFmUivCiIgHscmPsdgCyFj4Ccfx8BIBOGyaWsI4iYjiBLV4is1BUFoAwJgg9rECPVp6emjA2Ra3IR-VBydj4hDcXQdouATj9TaIUEs4C2RWxyLbe2roXQgBdEAA)

Result: true, but expected false, because `system` is not empty.

**Comment by plynchnlm** [comment]
I think this might be a bug in the FHIRPath Lab.  You had the context expression set to "value" but under Results it said the context was "value[0]" which is not correct for an Observation.  In the FHIRPath Lab, if you remove the context expression, then Observation.value.ofType(Quantity).system.empty() returns false as expected.

**Comment by brianpos** [comment]
While true, I think there are features that are more challenging to implement, working through that.
