### ISSUE TITLE
Inconsistent ".value" evaluation

### ISSUE THREAD

**Issue by lee-campbell** [HL7/fhirpath.js#158]
Steps to reproduce:

```javascript
const ctx = {
  resourceType: 'Parameters',
  parameter: [{
    name: 'param1',
    valueString: 'Value1',
  }, {
    name: 'param2',
    valueBoolean: true
  }]
};

const exp = "iif(parameter.where(name = 'param1').exists(), parameter.where(name = 'param1').value, 'UNKNOWN')";
const result = evaluate(ctx, exp);
expect(result[0]).toEqual('Value1'); // fails, returns []

const exp = "iif(parameter.where(name = 'param1').exists(), parameter.where(name = 'param1').valueString, 'UNKNOWN')";
const result = evaluate(ctx, exp);
expect(result[0]).toEqual('Value1'); // passes
```

Curiously, this works as expected at https://hl7.github.io/fhirpath.js/

**Comment by yuriy-sedinkin** [comment]
You need to pass a "model" to the `evaluate` function.
For example: `evaluate(ctx, exp, null, fhirpath_r4_model);`.
See README.md.

**Comment by lee-campbell** [comment]
Yes, the README absolutely says that:

"For FHIR-specific features (e.g. handling of choice type fields), you will also want to include a second file with the desired FHIR version model data."

My bad!
