### ISSUE TITLE
Link to FHIR Path documentation is incorrect

### ISSUE THREAD

**Issue by codebubb** [HL7/fhirpath.js#35]
In the readme file, the link to the documentation points to http://hl7.org/fhirpath/ which takes you to a page which has 500 error.

This should be updated to https://www.hl7.org/fhir/fhirpath.html presumably.

**Comment by plynchnlm** [comment]
Thanks for pointing out the problem but actually http://hl7.org/fhirpath/ is correct.  The page https://www.hl7.org/fhir/fhirpath.html is for the FHIR extensions to FHIRPath.  The best place to raise this issue would be on chat.fhir.org, in either the "implementers" or "fhirpath" streams.  However, I see someone has already done that:  https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/500.20error.20on.20website

The temporary workaround mentioned there is to add "index.html" to the URL.
