### ISSUE TITLE
IE 11 raises JS-Error

### ISSUE THREAD

**Issue by MenNoWar** [HL7/fhirpath.js#38]
When adding fhirpath.js in the resulting index.html IE 11 raises instantly a JS-Error.
This is in Versions 2.*, 1.0.2, 1.0.1
The only Version which could be successfully integrated with IE11 is Version 1.0.0.

**Comment by plynchnlm** [comment]
Thanks for the report.  I am hoping we can look into this next week.  Can you more specific about where you got fhirpath.js?  (Was it from the "release" zip file, or did you build it?)

**Comment by MenNoWar** [comment]
I got all the different fhirpath*.js files/versions from the zip-package(s) from the releases page.

As soon as the fhirpath.json is loaded (i don't even reach the point to get fhirpath.stu3.min.js afaik) i get the JavaScript Error Message in IE 11.
As always it is not really helpful, just saying JavaScript Error at Line 1, Position 1.

Between changing the releases (2, 1.0.2, 1.0.1) i always ensured to have cleared all possible caching of IE, so that at least this should not take part.

I am not reaching the point fhirpath.stu3.min.js as i guess, because the console log entry is never reached. At least i think to remember that JS-Files in the Header of a Html-Page are loaded syncronous and not asyncron.

`<head>
 ....
    <script src="./js/fhirpath.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        console.log("Loaded FhirPath");
    </script>
    <script src="./js/fhirpath.stu3.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        console.log("Loaded FhirPath STU3 Module");
    </script>
....
</head>`

**Comment by plynchnlm** [comment]
This should be fixed in 2.1.1.
