### ISSUE TITLE
Incorrect Link on README.md and question on implementation status

### ISSUE THREAD

**Issue by timharsch** [HL7/fhirpath.js#48]
The link in the README https://github.com/HL7/fhirpath.js/blame/01c7e185a47397cb5be124d0856bd409c486ff27/README.md#L121
Says that this project implements STU1 of FHIRPATH but points to the current STU2 of the standard.   If the goal of this project is still to implement STU1 then perhaps this link would be better:
http://hl7.org/fhirpath/2017Jan/index.html

Can someone comment on the current status of the project.. and any hints as to the road map would be very helpful for me as I am looking to include this awesome javascript library in my work going forward.

**Comment by brianpos** [comment]
I think this link has been updated and this issue can be closed @plynchnlm

**Comment by plynchnlm** [comment]
Thanks, @brianpos.  It looks like it has been updated.
