### ISSUE TITLE
Support for ofType for non-intrinsic types

### ISSUE THREAD

**Issue by timharsch** [HL7/fhirpath.js#50]
I was trying to use fhirpath to query my document with `Bundle.entry.resource.ofType(Observation)`   I expected a collection of non-zero size as result but received an empty collection.
I asked about this on the chat server and received a little insight from @plynchnlm.  FWIW: My document is here [DanielJohnson.Observations.json](https://gist.github.com/timharsch/80ebf952d4c784bbfa5542d9ca518b2d)

> ofType in fhirpath.js never got past types "integer" and "decimal", but I think the code to fully support it is nearly there.

**Comment by plynchnlm** [comment]
There is now limited support for ofType in 2.6.0.  (See the README for details.)  Let us know if that meets your needs raised here.  We plan to add more complete support, but it will require pulling in more data from the FHIR specification.

**Comment by plynchnlm** [comment]
It looks like support for ofType() should be complete as of 3.1.0.
