### ISSUE TITLE
Support for 'as' operator

### ISSUE THREAD

**Issue by timharsch** [HL7/fhirpath.js#51]
I was trying to use fhirpath to query my document with `Bundle.entry.select(resource as Observation)`   I expected a collection of non-zero size as result but received the error `Error: No TypeExpression evaluator`
I asked about this on the chat server and received a little insight from @plynchnlm.  FWIW: My document is here [DanielJohnson.Observations.json](https://gist.github.com/timharsch/80ebf952d4c784bbfa5542d9ca518b2d)

**Comment by alexzautke** [comment]
+1 :)

**Comment by plynchnlm** [comment]
It is in progress.  More work needs to be done to add support for type hierarchy.

**Comment by plynchnlm** [comment]
Support for the "as" operator and function was added in 3.1.0.  Please give it a try.
