### ISSUE TITLE
DSTU2 support

### ISSUE THREAD

**Issue by timharsch** [HL7/fhirpath.js#52]
There are a large number of EHR providers that provide information in DSTU2 format.  It would be useful if fhirpath.js could support that older standard.

Per discussion with @plynchnlm 
> Without the model information, fhirpath.js will still mostly work, but type information will be absent, so things like the "as" operator won't work. Also, choice type support will be lacking, so you won't be able to do Observation.value, but would have to write Observation.valueString (which is the actual field name in the JSON).
>
> FYI, if the FHIR definitions are in the same format for DSTU2 as for STU3 (which I have not checked), it would not be difficult to generate model information for DSTU2 and add that to fhirpath.js.

**Comment by plynchnlm** [comment]
Thanks for filing this.  I have added it to our task list.

**Comment by plynchnlm** [comment]
DSTU2 support has been added in 2.4.0.
