### ISSUE TITLE
iif - third expression is optional

### ISSUE THREAD

**Issue by plynchnlm** [HL7/fhirpath.js#6]
Per the spec, the third expression passed to iif is optional, and if left out it is equivalent to passing in the empty collection { }.

[Copied from https://github.com/lhncbc/fhirpath.js/issues/75]

**Comment by brianpos** [comment]
@plynchnlm I think you can close this one, seems to be fine to me now.

**Comment by plynchnlm** [comment]
Fixed in version 2.3.0.
