### ISSUE TITLE
Warning due to antlr4 dependency when using Node.js 14

### ISSUE THREAD

**Issue by 7opf** [HL7/fhirpath.js#64]
When using fhirpath.js as a dependency of a node 14 project, the following warning is printed due to antlr4:
```
Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```
Seems to be resolved in antlr 4.9, tracked in this issue: https://github.com/antlr/antlr4/issues/2834

**Comment by plynchnlm** [comment]
Thanks for the report.  I've created an issue to update both Node.js and antlr.  Is this an annoyance or is it causing something to break?

**Comment by 7opf** [comment]
I haven't noticed anything breaking due to this

**Comment by plynchnlm** [comment]
Okay, thanks.  I've added it to our list to try to update both antlr4 and Node.js.

**Comment by plynchnlm** [comment]
It seems that antlr 4.9 requires Node.js 14, so we can't update antlr until Node.js 10 & 12 are no longer needed.

**Comment by plynchnlm** [comment]
We are now at ANTLR 4.9.3. and Node.js 16, so I think this is resolved.
