### ISSUE TITLE
Error: Expected boolean, got: "Jim"

### ISSUE THREAD

**Issue by mohammadfarooqi** [HL7/fhirpath.js#71]
I am trying to use "OR", section 6.8 #12 on http://hl7.org/fhirpath/#operator-precedence.
However, it looks like the Fhirpath understands what OR is, but for some reason I get "Error: Expected boolean, got: Jim"

Here is an image. 

![image](https://user-images.githubusercontent.com/10905290/110705062-d5c51180-81c3-11eb-95a0-905a7646cf3f.png)

Wondering if there is some sort of type casting I am missing?

**Comment by plynchnlm** [comment]
That might be a bug.  The expected type of the operands for the "or" operator is Boolean, and singleton items (["Jim"]) are supposed to be converted to true when a Boolean expected, per http://hl7.org/fhirpath/#singleton-evaluation-of-collections.  Note that if there were more than one name in the array, then per the same part of the specification an error would be expected.  We will look into this.  In the meantime, you could probably append .exists() to each to explicitly convert it to a Boolean.

**Comment by mohammadfarooqi** [comment]
@plynchnlm got it, 

I am actually trying to get "Jim" back. The idea is, If the family name exists, then provide that, else provide given name. 

I know we can do this through `iif`, but the problem with iif is that the nested gets quite confusing when writing it out. 

Is there any other way to request the following:
Give back "family" or "given" or "date of birth".

The hope here is to get back if family exists, or else given, or else date of birth. If all exists, then the first one is ok.

**Comment by plynchnlm** [comment]
Patient.name.where(use='usual').select(family | given)[0].  If you want the birth date in there, it will get a little more complicated.  If you have further questions along these lines, it is probably best to move the discussion to chat.fhir.org.  I am glad you pointed out the bug, though.

**Comment by akanduru** [comment]
Is boolean operator supposed to be case insensitive? The expression seems to work with OR...

**Comment by plynchnlm** [comment]
"OR" is not valid.  The reason it appears to accept it is due to a error with the parsing which causes it to ignore remaining input when it encounters something it does not recognize.  It should raise an error.  I will add this to our list of things to fix as well.

**Comment by mohammadfarooqi** [comment]
@plynchnlm thanks a lot . this is much appreciated.

**Comment by plynchnlm** [comment]
Just a note that in my suggested expression above, "family | given" should work for fhirpath.js, but the specification says there is no expectation of order for a union operation (|).  So, another implementation of FHIRPath might return "given" first (though I am not sure why it would do that).

**Comment by plynchnlm** [comment]
Just a note that in my suggested expression above, "family | given" should work for fhirpath.js, but the specification says there is no expectation of order for a union operation (|).  So, another implementation of FHIRPath might return "given" first (though I am not sure why it would do that).  So, I think this might be better:  Patient.name.where(use='official').select(iif(family.exists(), family, given[0]))

**Comment by plynchnlm** [comment]
These issues are fixed in 2.7.4.
