### ISSUE TITLE
`contains` not correctly handling empty collection inputs

### ISSUE THREAD

**Issue by okeefm** [HL7/fhirpath.js#74]
In testing some FHIRPath in https://hl7.github.io/fhirpath.js/, I wrote the following piece of FHIRPath, against the default JSON patient: 

`Patient.telecom.where(system = 'phone' and value.contains('@')).empty()`

However, instead of returning `true`, as expected, I get the error `Error: Expected string, but got []`.

This appears to be caused by the `telecom` element that doesn't have a value, just a `use`. If this element is removed, the error goes away. 

It seems that the `value.contains('@')` may not be properly returning an empty collection (`{}`) when the input is empty, as is specified in its definition: http://hl7.org/fhirpath/N1/#containssubstring-string-boolean.

With the mostly-empty `telecom` element present:
<img width="1200" alt="Screen Shot 2021-04-06 at 4 46 02 PM" src="https://user-images.githubusercontent.com/49001/113776237-b4d6da00-96f7-11eb-842f-c9257dfb3b14.png">

With the mostly-empty `telecom` element removed
<img width="1014" alt="Screen Shot 2021-04-06 at 4 46 22 PM" src="https://user-images.githubusercontent.com/49001/113776250-b7d1ca80-96f7-11eb-8d91-20c14174d40a.png">

**Comment by plynchnlm** [comment]
Yes, that looks like a bug.  How urgently do you need this fixed?

**Comment by okeefm** [comment]
@plynchnlm Not super urgently. I've been able to find "defensive FHIRPath" that gets around the issue pretty easily. Just thought I should bring it up so it was known.

**Comment by plynchnlm** [comment]
Definitely -- thanks for taking the time to report it.  In that case, it will probably take us 3-4 weeks to get to it.

**Comment by plynchnlm** [comment]
This is now fixed in 2.8.0.  Thanks for reporting the issue.
