### ISSUE TITLE
IE 10 support needed

### ISSUE THREAD

**Issue by plynchnlm** [HL7/fhirpath.js#8]
Copied from the old repository, at https://github.com/lhncbc/fhirpath.js/issues/63:

Someone at Cerner told me that EHR systems are still using an IE 10 browser plugin. Support for Edge is on the way, but it will be about 5 years until 1) the new version is out and 2) customers upgrade to it.

I suspect webpack/babel can handle most issues for us.

Update:  I confirmed that the demo does not run in IE 10 using an virtual machine downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by bpacJoseph** [comment]
I managed to get it working in ie 10. Do you want a pull request for it?

**Comment by plynchnlm** [comment]
Yes, thanks.  That would be very helpful.

**Comment by bpacJoseph** [comment]
https://github.com/HL7/fhirpath.js/pull/19
